# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "Tie::IxHash" => "0";
requires "XML::DOM" => "1.46";
requires "perl" => "5.008";

on 'test' => sub {
  requires "Test" => "0";
};

on 'configure' => sub {
  requires "ExtUtils::MakeMaker" => "0";
};

on 'develop' => sub {
  requires "Test::Pod" => "1.41";
  requires "Test::Spelling" => "0.12";
};
